### ISSUE TITLE
Prevent CI running on draft PRs?

### ISSUE THREAD

**Issue by Andrew-Morozko** [blackstork-io/fabric#89]
We can do it by adding if conditions on the jobs:

```yml

jobs:
  tests:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    <...>
```

I think running CI on unfinished code is not useful
